name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y ffmpeg
        pip install pygame-ce==2.5.4 pygbag==0.9.2 black
        pip install numpy pygame_gui python-i18n
    
    - name: Build with pygbag
      run: |
        timeout 600 python -m pygbag --build .
    
    - name: Check build output
      run: |
        echo "Contents of current directory:"
        ls -la
        echo "Contents of build directory:"
        ls -la build/ || echo "No build directory"
        echo "Looking for index.html:"
        find . -name "index.html" -type f
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
