name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pygame-ce==2.5.4 pygbag==0.9.2
        pip install -r requirements.txt
    
    - name: Build with pygbag
      run: python -m pygbag main.py
    
    - name: Find and verify build files
      run: |
        echo "Looking for index.html..."
        find . -name "index.html" -type f
        echo "Files in current directory:"
        ls -la
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
