name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install Python dependencies
      run: |
        pip install pygame-ce==2.5.4 pygbag==0.9.2 black
        pip install -r requirements.txt
    
    - name: Configure WASM
      run: |
        mkdir -p ~/.config/pygbag
        echo '{"wasm_mimetype": "application/wasm"}' > ~/.config/pygbag/config.json
    
    - name: Build for web
      run: |
        python -m pygbag .
    
    - name: Verify build output
      run: |
        echo "Checking build output directory..."
        ls -la ./build/web/
        echo "Checking for main.wasm..."
        test -f ./build/web/main.wasm
        echo "Checking for index.html..."
        test -f ./build/web/index.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
