name: Deploy with Pygbag

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y ffmpeg
        pip install pygame-ce==2.5.4 pygbag==0.9.2 black numpy==1.24.3 pygame_gui==0.6.13 python-i18n==0.3.9
    
    - name: Build with pygbag
      run: python -m pygbag --build main.py
      timeout-minutes: 10
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
